version: 2.1
jobs:
  build:
    docker:
      - image: "crazyuploader/python_build_tools:latest"
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Running main.py
          command: |
            python main.py
