version: 2.1
jobs:
  build:
    docker:
      - image: "python:3.13-bookworm"
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: |
            pip install pipenv
            pipenv install
      - run:
          name: Running main.py
          command: |
            pipenv run python main.py
