name: Python
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
jobs:
  python_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyflakes flake8

      - name: Check Program
        run: |
          curl -s https://raw.githubusercontent.com/crazyuploader/Bash/master/check_py.sh | bash -
      
      - name: Run Program
        run: |
          chmod +x main.py
          ./main.py
