name: Python
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:
jobs:
  python_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.9"

      - name: Installing Dependencies
        run: |
          pip install --upgrade pip
          pip install pyflakes flake8

      - name: Check Program
        run: |
          curl -s https://raw.githubusercontent.com/crazyuploader/Bash/master/check_py.sh | bash -
